# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created: Thu Oct  8 20:30:06 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1056, 766)
        self.Centralwidget = QtGui.QWidget(MainWindow)
        self.Centralwidget.setObjectName(_fromUtf8("Centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.Centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.console_header = QtGui.QGroupBox(self.Centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(189, 189, 189))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(180, 180, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(189, 189, 189))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(180, 180, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(189, 189, 189))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.console_header.setPalette(palette)
        self.console_header.setObjectName(_fromUtf8("console_header"))
        self.gridLayout.addWidget(self.console_header, 3, 0, 1, 1)
        self.console = QtGui.QPlainTextEdit(self.Centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.console.setPalette(palette)
        self.console.setObjectName(_fromUtf8("console"))
        self.gridLayout.addWidget(self.console, 4, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.Centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(981, 0))
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.roadmap_tab = QtGui.QWidget()
        self.roadmap_tab.setObjectName(_fromUtf8("roadmap_tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.roadmap_tab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.roadmap_group = QtGui.QGroupBox(self.roadmap_tab)
        self.roadmap_group.setObjectName(_fromUtf8("roadmap_group"))
        self.roadmap_Options = QtGui.QPushButton(self.roadmap_group)
        self.roadmap_Options.setGeometry(QtCore.QRect(0, 50, 91, 27))
        self.roadmap_Options.setObjectName(_fromUtf8("roadmap_Options"))
        self.roadmap_Run = QtGui.QPushButton(self.roadmap_group)
        self.roadmap_Run.setGeometry(QtCore.QRect(0, 80, 91, 27))
        self.roadmap_Run.setObjectName(_fromUtf8("roadmap_Run"))
        self.roadmap_frame = QtGui.QFrame(self.roadmap_group)
        self.roadmap_frame.setGeometry(QtCore.QRect(100, 10, 881, 431))
        self.roadmap_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.roadmap_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.roadmap_frame.setObjectName(_fromUtf8("roadmap_frame"))
        self.roadmap_widget = matplotlibWidget(self.roadmap_frame)
        self.roadmap_widget.setGeometry(QtCore.QRect(140, -40, 581, 501))
        self.roadmap_widget.setObjectName(_fromUtf8("roadmap_widget"))
        self.gridLayout_2.addWidget(self.roadmap_group, 0, 0, 1, 1)
        self.tabWidget.addTab(self.roadmap_tab, _fromUtf8(""))
        self.polygons_tab = QtGui.QWidget()
        self.polygons_tab.setObjectName(_fromUtf8("polygons_tab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.polygons_tab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.polygons_group = QtGui.QGroupBox(self.polygons_tab)
        self.polygons_group.setObjectName(_fromUtf8("polygons_group"))
        self.polygons_Options = QtGui.QPushButton(self.polygons_group)
        self.polygons_Options.setGeometry(QtCore.QRect(0, 50, 91, 27))
        self.polygons_Options.setObjectName(_fromUtf8("polygons_Options"))
        self.polygons_Run = QtGui.QPushButton(self.polygons_group)
        self.polygons_Run.setGeometry(QtCore.QRect(0, 80, 91, 27))
        self.polygons_Run.setObjectName(_fromUtf8("polygons_Run"))
        self.frame_2 = QtGui.QFrame(self.polygons_group)
        self.frame_2.setGeometry(QtCore.QRect(100, 10, 891, 431))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.polygons_widget = matplotlibWidget(self.frame_2)
        self.polygons_widget.setGeometry(QtCore.QRect(140, -40, 581, 501))
        self.polygons_widget.setObjectName(_fromUtf8("polygons_widget"))
        self.gridLayout_3.addWidget(self.polygons_group, 0, 0, 1, 1)
        self.tabWidget.addTab(self.polygons_tab, _fromUtf8(""))
        self.building_generation_tab = QtGui.QWidget()
        self.building_generation_tab.setObjectName(_fromUtf8("building_generation_tab"))
        self.gridLayout_4 = QtGui.QGridLayout(self.building_generation_tab)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.building_generation_group = QtGui.QGroupBox(self.building_generation_tab)
        self.building_generation_group.setObjectName(_fromUtf8("building_generation_group"))
        self.building_generation_Options = QtGui.QPushButton(self.building_generation_group)
        self.building_generation_Options.setGeometry(QtCore.QRect(0, 50, 91, 27))
        self.building_generation_Options.setObjectName(_fromUtf8("building_generation_Options"))
        self.building_generation_Run = QtGui.QPushButton(self.building_generation_group)
        self.building_generation_Run.setGeometry(QtCore.QRect(0, 80, 91, 27))
        self.building_generation_Run.setObjectName(_fromUtf8("building_generation_Run"))
        self.frame_3 = QtGui.QFrame(self.building_generation_group)
        self.frame_3.setGeometry(QtCore.QRect(120, 10, 881, 431))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout_4.addWidget(self.building_generation_group, 0, 0, 1, 1)
        self.tabWidget.addTab(self.building_generation_tab, _fromUtf8(""))
        self.visualization_tab = QtGui.QWidget()
        self.visualization_tab.setObjectName(_fromUtf8("visualization_tab"))
        self.gridLayout_5 = QtGui.QGridLayout(self.visualization_tab)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.visualization_group = QtGui.QGroupBox(self.visualization_tab)
        self.visualization_group.setObjectName(_fromUtf8("visualization_group"))
        self.visualization_Options = QtGui.QPushButton(self.visualization_group)
        self.visualization_Options.setGeometry(QtCore.QRect(0, 50, 91, 27))
        self.visualization_Options.setObjectName(_fromUtf8("visualization_Options"))
        self.visualization_Run = QtGui.QPushButton(self.visualization_group)
        self.visualization_Run.setGeometry(QtCore.QRect(0, 80, 91, 27))
        self.visualization_Run.setObjectName(_fromUtf8("visualization_Run"))
        self.frame_4 = QtGui.QFrame(self.visualization_group)
        self.frame_4.setGeometry(QtCore.QRect(120, 10, 881, 431))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.gridLayout_5.addWidget(self.visualization_group, 0, 0, 1, 1)
        self.tabWidget.addTab(self.visualization_tab, _fromUtf8(""))
        self.advanced_tab = QtGui.QWidget()
        self.advanced_tab.setObjectName(_fromUtf8("advanced_tab"))
        self.gridLayout_6 = QtGui.QGridLayout(self.advanced_tab)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.advancd_group = QtGui.QGroupBox(self.advanced_tab)
        self.advancd_group.setObjectName(_fromUtf8("advancd_group"))
        self.clean_directories = QtGui.QPushButton(self.advancd_group)
        self.clean_directories.setGeometry(QtCore.QRect(10, 30, 201, 27))
        self.clean_directories.setObjectName(_fromUtf8("clean_directories"))
        self.run_tests = QtGui.QPushButton(self.advancd_group)
        self.run_tests.setGeometry(QtCore.QRect(10, 60, 201, 27))
        self.run_tests.setObjectName(_fromUtf8("run_tests"))
        self.gridLayout_6.addWidget(self.advancd_group, 0, 0, 1, 1)
        self.tabWidget.addTab(self.advanced_tab, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.Centralwidget)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Procedural City Generation", None))
        self.console_header.setTitle(_translate("MainWindow", "       Console", None))
        self.roadmap_group.setTitle(_translate("MainWindow", "Commands", None))
        self.roadmap_Options.setText(_translate("MainWindow", "Options", None))
        self.roadmap_Run.setText(_translate("MainWindow", "Run", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.roadmap_tab), _translate("MainWindow", "Roadmap Generation", None))
        self.polygons_group.setTitle(_translate("MainWindow", "Commands", None))
        self.polygons_Options.setText(_translate("MainWindow", "Options", None))
        self.polygons_Run.setText(_translate("MainWindow", "Run", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.polygons_tab), _translate("MainWindow", "Polygon Extraction", None))
        self.building_generation_group.setTitle(_translate("MainWindow", "Commands", None))
        self.building_generation_Options.setText(_translate("MainWindow", "Options", None))
        self.building_generation_Run.setText(_translate("MainWindow", "Run", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.building_generation_tab), _translate("MainWindow", "Building Generation", None))
        self.visualization_group.setTitle(_translate("MainWindow", "Commands", None))
        self.visualization_Options.setText(_translate("MainWindow", "Options", None))
        self.visualization_Run.setText(_translate("MainWindow", "Run", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.visualization_tab), _translate("MainWindow", "Visualize in Blender", None))
        self.advancd_group.setTitle(_translate("MainWindow", "GroupBox", None))
        self.clean_directories.setText(_translate("MainWindow", "Clean Directories", None))
        self.run_tests.setText(_translate("MainWindow", "Run Tests", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.advanced_tab), _translate("MainWindow", "Advanced", None))

from GUI import matplotlibWidget
